baseURL = "https://eikebergmann.de/"
languageCode = "de"
DefaultContentLanguage = "de"
title = "Eike Bergmann | Solution Architect, Software Engineer, all-around coder"
theme = "raditian"

# Languages
#   de
#     weight: 1
#   en
#     weight: 2

[build]
  writeStats = true
  
# Additional CSS and JS
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "css/main.css"
  [[params.plugins.css]]
  link = "css/rad-icons.css"
  [[params.plugins.css]]
  link = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
 

# Main navigation menu
[menu]

  [[menu.header]]
  name = "Über mich"
  URL = "index.html#about"
  weight = 2

  [[menu.header]]
  name = "Erfahrung"
  URL = "index.html#experience"
  weight = 3

  [[menu.header]]
  name = "Kontakt"
  URL = "#contact"
  weight = 4

  [[menu.footer]]
  name = "Über mich"
  URL = "index.html#about"
  weight = 2

  [[menu.footer]]
  name = "BÜcher"
  URL = "/books"
  weight = 3

  [[menu.footer]]
  name = "Public Speaking"
  URL = "/public-speaking"
  weight = 4

  [[menu.footer]]
  name = "Kontakt"
  URL = "index.html#contact"
  weight = 5


# Misc settings
[params]
  sections = ["showcase", "about", "education", "experience", "contact"]
  googleTagManagerID = "GTM-PMWF2QQ" # Google Analytics works with Google Tag Manager

  [params.logo]
    text1 = "Eike"
    text2 = "Bergmann"

  [params.footer]
      copyright = "© Eike Bergmann. <a href=\"https://github.com/eikeb/eikebergmann.de\">Code available in GitHub</a>."

[taxonomies]
  book_author = "book_authors"
  book_category = "book_categories"